CREATE TABLE Materials1 (
    MaterialID INTEGER PRIMARY KEY AUTOINCREMENT,
    MaterialNameAR VARCHAR(255),
    MaterialNameEN VARCHAR(255),
    MaterialCost DECIMAL(10, 2),
    MaterialSize DECIMAL(10, 2),
    UnitType VARCHAR(50)
);

INSERT INTO Materials1 (MaterialNameAR, MaterialNameEN, MaterialCost, MaterialSize, UnitType)
VALUES 
('لوح فلين', 'Corkboard', 23, 1, 'mm'),
('لوح زجاجي', 'Glass slab', 16, 1, 'mm'),
('مسطرة', 'Ruler', 9, 1, 'mm'),
('منقلة', 'Protractor', 6, 3, 'mm'),
('دبوس', 'Pin', 6, 0.02, 'mm'),
('قلم رصاص', 'Pencile', 5, 0.42, 'mm'),
('أوراق بيضاء', 'White papers', 44, 0.011, 'mm'),
('ميزان بالقصور الذاتي', 'Inertial balance', 41, 1, 'mm'),
('ميزان إلكتروني', 'Electronic balance', 108, 1, 'mm'),
('كتل مجهولة', 'Unknown masses', 16, 4, 'mm'),
('ساعة إيقاف', 'Stopwatch', 30, 2.5, 'mm'),
('ملح', 'salt', 2, 0.002, 'mm'),
('محلول سائل غسيل أطباق', 'dishwashing liquid solution', 10, 0.0133, 'mm'),
('أسطوانة مدرجة بسعة', 'graduated cylinder with a capacity', 20, 10, 'mm'),
('ملعقة مسطحة', 'spatula spoon', 14, 0.64, 'mm'),
('كأس يحتوي على', 'beaker containing', 10, 10, 'mm'),
('ماء', 'Water', 3, 0.003, 'mm'),
('أسطوانة مدرجة بسعة 300 مل', 'graduated cylinder with a 300 mL capacity', 24, 12, 'mm'),
('أكواب', 'beakers', 26, 4.33, 'mm'),
('ملعقة خشبية', 'wooden spoon', 25, 0.08, 'mm'),
('أسلاك كهربائية', 'electrical wires', 16, 0.08, 'mm'),
('مصباح كهربائي', 'electric bulb', 12, 2, 'mm'),
('بطارية جافة ضعيفة (قديمة).', 'A weak (old) dry battery.', 1, 1, 'mm'),
('بطارية جافة', 'dry battery', 8, 2, 'mm'),
('شاشة بيضاء', 'white screen', 12, 12, 'mm'),
('مسار متدرج مع عدة حوامل متحركة عليه.', 'graduated track and several movable holders on it.', 15, 15, 'mm'),
('صندوق إضاءة', 'light box', 37, 37, 'mm'),
('عدسة محدبة', 'convex lens', 17, 2.83, 'mm'),
('فلفل أسود', 'Black pepper', 4, 0.004, 'mm'),
('بالون', 'balloon', 8, 0.07, 'mm'),
('طبق بتري', 'petri dish', 15, 0.5, 'mm'),
('ملعقة', 'spoon', 22, 0.06, 'mm'),
('قضبان إيبونيت', 'ebonite rods', 9, 9, 'mm'),
('قطعة حرير', 'piece of silk', 7, 7, 'mm'),
('قضيب زجاجي', 'glass rod', 14, 1.4, 'mm'),
('شرائط ورقية', 'Paper strips', 20, 0.25, 'mm'),
('مصباح كهربائي', 'light bulb', 12, 2, 'mm'),
('بطارية', 'battery', 8, 2, 'mm'),
('مفتاح', 'switch', 10, 1.67, 'mm'),
('مصباحان كهربائيان بمقاومتين مختلفتين', '2 light bulbs with different resistance', 12, 2, 'mm'),
('مصدر جهد كهربائي', 'electrical voltage source', 8, 2, 'mm'),
('فولتميتر', 'voltmeter', 25, 25, 'mm'),
('منشور زجاجي', 'glass prism', 32, 2.67, 'mm'),
('حاجز كرتوني متين', 'sturdy cardboard barrier', 20, 0.4, 'mm'),
('أنابيب تفريغ (هيليوم، هيدروجين، نيون)', 'discharge tubes (helium, hydrogen, neon)', 57, 57, 'mm'),
('حامل معدني', 'Metal holder', 38, 38, 'mm'),
('بوابة ضوئية مزودة بمؤقتات', 'photogate with timers', 320, 320, 'mm'),
('بعض الأسلاك', 'Some wires', 16, 0.08, 'mm'),
('شريط قياس', 'measuring tape', 10, 5, 'mm'),
('مجموعة أوزان متساوية الكتلة', 'group of weights with an equal mass', 16, 4, 'mm'),
('حامل أوزان', 'weight holder', 10, 10, 'mm'),
('زنبرك', 'spring', 10, 1, 'mm'),
('كرة', 'ball', 17, 1.42, 'mm'),
('مسار محدد', 'Marked-off track', 10, 10, 'mm'),
('مؤقت', 'timer', 16, 16, 'mm'),
('مسار متدرج', 'graduated track', 10, 10, 'mm'),
('أداة ضبط الارتفاع', 'height adjustment tool', 19, 19, 'mm'),
('سيارة لعبة', 'toy car', 10, 1.25, 'mm'),
('طاولة قوى', 'Force table', 169, 169, 'mm'),
('مجموعة أوزان مختلفة الكتل', 'set of weights of different masses', 16, 4, 'mm'),
('كرتان مختلفتا الكتل ومتقاربتا الحجم', '2 spheres with different masses and approximately the same volume', 10, 5, 'mm'),
('صندوق كرتوني صغير مفتوح', 'small open cardboard box', 23, 0.46, 'mm'),
('وعاء', 'bowl', 10, 10, 'mm'),
('علبة معدنية', 'metal can', 14, 14, 'mm'),
('وعاء بلاستيكي', 'plastic bowl', 10, 0.1, 'mm'),
('ماء ساخن', 'Hot water', 3.5, 2.14, 'mm'),
('ماء بارد', 'Cold water', 3, 0.003, 'mm'),
('حاملات ميزان حرارة', 'Thermometer holders', 10, 2.5, 'mm'),
('نموذج رافعة بسيط', 'simple lever model', 15, 15, 'mm'),
('مجموعة أوزان، لكل منها كتلة', 'set of weights, each with a mass', 16, 4, 'mm'),
('حاملات أوزان بكتلة', 'weight carriers with a mass', 23, 11.5, 'mm'),
('مسار معدني أملس', 'smooth metallic track', 107, 17.83, 'mm'),
('جهاز ضبط الارتفاع', 'height adjustment device', 64, 64, 'mm'),
('خيط رفيع بطول متر واحد', 'Thin string of 1 m length', 9, 0.04, 'mm'),
('ميزان زنبركي', 'spring balance', 13, 13, 'mm'),
('مكعبات خشبية', 'Wooden cubes', 37, 0.62, 'mm'),
('مجموعة أوزان مختلفة', 'set of different masses', 16, 4, 'mm'),
('بكرة ​​ملساء', 'smooth pulley', 13, 1.08, 'mm'),
('أقماع شفافة', 'transparent funnels', 12, 3, 'mm'),
('حوامل معدنية', 'metal stands', 37, 37, 'mm'),
('جلسرين', 'Glycerin', 34, 0.009, 'mm'),
('مقياس فنتوري', 'Venturi meter', 15, 15, 'mm'),
('حوض ماء', 'basin of water', 17, 17, 'mm'),
('مقياس ضغط', 'manometer', 40, 40, 'mm'),
('عربة ميكانيكية', 'Mechanical trolley', 100, 100, 'mm'),
('مصدر تطبيق قوة الدفع', 'Thrust force application source', 10, 10, 'mm'),
('مكعبات معدنية مختلفة الكتل', 'metal cubes of different masses', 38, 5.43, 'mm'),
('حاجز', 'Barrier', 20, 0.4, 'mm'),
('مسار معدني', 'metal track', 10, 5, 'mm'),
('بوابات ضوئية', 'photo gates', 167, 167, 'mm'),
('منظم ارتفاع', 'height adjuster', 64, 64, 'mm'),
('كرة معدنية', 'metal ball', 10, 2.5, 'mm'),
('وعاء بلاستيكي عميق', 'deep plastic container', 17, 17, 'mm'),
('زجاجة بلاستيكية', 'plastic bottle', 37, 6.17, 'mm'),
('مثقاب إبرة', 'needle drill', 10, 10, 'mm'),
('مقص', 'scissors', 11, 3.67, 'mm'),
('مادة لاصقة', 'adhesive', 30, 10, 'mm'),
('أسطوانة مدرجة', 'graduated cylinder.', 23, 11.5, 'mm'),
('أكواب إزاحة، بسعة', 'displacement beakers, with a capacity', 40, 3.33, 'mm'),
('حلقة مطاطية', 'rubber ring', 7, 0.14, 'mm'),                                                                                                     

('أنبوب زجاجي', 'glass tube', 27, 1.125, 'Object'),
('قطعة من الورق المقوى', 'piece of cardboard', 23, 0.23, 'Object'),
('نشارة خشب', 'Wood shavings', 13, 0.013, 'gram'),
('سدادة فلين', 'cork stopper', 7, 0.35, 'piece'),
('دورق حجمي', 'volumetric flask', 50, 16.66666667, 'object'),
('موقد بنسن', 'bunsen burner', 12, 12, 'object'),
('فيرنييه', 'vernier', 8, 8, 'object'),
('ميكرومتر', 'micrometer', 16, 16, 'object'),
('شريط متري', 'metric tape', 8, 4, 'object'),
('سيارة ميكانيكية', 'mechanical car', 24, 4, 'Car'),
('ميزان زنبركي', 'spring scale', 12, 12, 'object'),
('سطح أملس', 'smooth surface', 25, 12.5, 'Object'),
('كوب بلاستيكي', 'Object', 30, 0.125, 'object'),
('خيط', 'String', 9, 0.036, 'meter'),
('مصاصات بلاستيكية', 'plastic straws', 15, 0.025, 'object'),
('طين', 'Clay', 1, 1, 'gram'),
('أسطوانة حديدية', 'iron cylinder', 20, 5, 'object'),
('حامل ثلاثي القوائم', 'tripod stand', 16, 16, 'object'),
('عدسات محدبة', 'convex lenses', 14, 2.333333333, 'object'),
('مضخة هواء كهربائية', 'electric air pump', 12, 6, 'object'),
('مكعبات ثلج', 'ice cubes', 3, 0.003, 'mL'),
('برطمان زجاجي بغطاء', 'glass jar with a lid', 20, 3.333333333, 'object'),
('كأس ماء ساخن', 'beaker of hot water', 3.5, 2.14, 'mL'),
('ملقط أكواب', 'Beaker tongs', 17, 5.666666667, 'object'),
('ملون طعام أحمر وأزرق', 'Red and blue food coloring', 10, 0.625, 'object'),
('قضبان تحريك زجاجية', 'glass stirring rods', 20, 1.666666667, 'object'),
('دبابيس ورقية', 'paper pins', 10, 0.357142857, 'object'),
('حصى', 'Gravel', 10, 0.2, 'object'),
('رمل', 'Sand', 20, 0.2, 'gram'),
('عينات صخرية', 'Rock samples', 16, 16, 'object'),
('حمض الهيدروكلوريك المخفف (HCI)', 'Diluted hydrochloric acid (HCI)', 40, 0.08, 'ml'),
('مطرقة', 'hammer', 7, 7, 'Object'),
('خلاط كهربائي', 'electric mixer', 17, 17, 'object'),
('وعاء ماء', 'container containing water', 10, 0.1, 'object'),
('قصاصات ورق من دفاتر', 'Paper scraps from notebooks', 19, 0.031666667, 'object'),
('سكين', 'Knife', 30, 30, 'object'),
('معدن غالينا، معدن ميكا، معدن كوارتز', 'Galena mineral, Mica mineral, Quartz mineral', 47, 0.376, 'gram'),
('زيت', 'Oil', 46, 0.092, 'ml'),
('ماصة', 'Pipette', 13, 0.043333333, 'object'),
('أكواب زجاجية بسعة', 'beakers with a capacity', 40, 3.333333333, 'Object'),
('إبريق سقاية يحتوي على ماء ملون', 'watering can containing colored water', 23, 23, 'Object'),
('طين جاف', 'Dry clay', 1, 1, 'gram'),
('رمل جاف', 'Dry sand', 1, 1, 'gram'),
('مجرفة يدوية صغيرة', 'small hand shovel', 26, 2.166666667, 'object'),
('مجهر بصري مركب', 'Compound optical microscope', 150, 150, 'object'),
('مشرط تشريح', 'scalpel', 7, 0.7, 'object'),
('ملقط', 'Forceps', 16, 2.285714286, 'object'),
('عدسة مكبرة/عدسة مكبرة', 'Magnifying glass/lens', 10, 5, 'object'),
('أنابيب اختبار', 'Test tubes', 29, 0.604166667, 'object'),
('أنبوب اختبار رف', 'Test tube rack', 13, 4.333333333, 'object'),
('قطارة', 'Dropper', 13, 0.043333333, 'object'),
('شريحة زجاجية', 'Glass slide', 14, 0.097222222, 'object'),
('أغطية أغطية', 'Cover slips', 13, 0.0013, 'object'),
('أسطوانات مدرجة', 'Graduated cylinders', 24, 12, 'object'),
('قمع', 'Funnel', 12, 3, 'Object'),
('ورق ترشيح', 'Filter paper', 11, 0.11, 'object'),
('طبق بتري', 'Petri dish', 15, 0.5, 'object'),
('زجاجة غسيل', 'Water wash bottle', 30, 7.5, 'object'),
('ملقط', 'Cubicle tongs', 8, 2.666666667, 'object'),
('ورق زبدة', 'Butter paper', 16, 0.106666667, 'object'),
('مناشف ورقية', 'Paper towels', 23, 0.23, 'object'),
('صواني مختبرية', 'Laboratory trays', 10, 5, 'object'),
('أكياس بلاستيكية شفافة قابلة للإغلاق', 'Transparent, sealable plastic bags', 23, 0.115, 'object'),
('كحول إيثيلي (96%)', 'Ethyl alcohol (96%)', 154, 0.154, 'ml'),
('حمض هيدروكلوريك مخفف بنسبة 10%', '10% diluted hydrochloric acid (HCl)', 74, 0.074, 'ml'),
('محلول تلوين أسيتوكارمين', 'Acetocarmine staining solution', 20, 0.04, 'ml'),
('محلول لوغول', 'Lugol''s solution', 25, 0.25, 'ml'),
('بيكربونات الصوديوم', 'Sodium bicarbonate', 58, 0.116, 'gram'),
('صبغة اليود', 'Iodine stain', 6, 0.012, 'ml'),
('خل أبيض', 'White vinegar', 4, 0.001, 'ml'),
('محلول نشا', 'Starch solution', 5, 0.005, 'gram'),
('محلول فيتامين ج', 'Vitamin C solution', 40, 0.666666667, 'ml'),
('عصير برتقال طازج', 'Fresh orange juice', 3, 3, 'ml'),
('عصير برتقال تجاري', 'Commercial orange juice', 3, 3, 'ml'),
('حمض هيدروكلوريك بتركيز محدد', 'Hydrochloric acid at a specified concentration', 74, 0.074, 'ml'),
('هيدروكسيد الصوديوم بتركيز محدد', 'Sodium hydroxide at a specified concentration', 30, 0.03, 'ml'),
('بصل', 'Onion', 3, 3, 'object'),
('بطاطس', 'Potato', 3, 3, 'object'),
('طماطم', 'Tomato', 3, 3, 'object'),
('كمثرى', 'Pear fruit', 3, 3, 'object'),
('الفراولة', 'Strawberry', 3, 3, 'object'),
('البرتقال', 'Orange', 3, 3, 'object'),
('نبات المشمش (أوراق، أزهار، جذور)', 'Apricot plant (leaves, flowers, roots)', 3, 3, 'object'),
('نبات الليمون (أوراق، أزهار، جذور)', 'Lemon plant (leaves, flowers, roots)', 3, 3, 'object'),
('نبات البصل (أوراق، أزهار، جذور)', 'Onion plant (leaves, flowers, roots)', 3, 3, 'object'),
('نبات السوسن (أوراق، أزهار، جذور)', 'Iris plant (leaves, flowers, roots)', 3, 3, 'object'),
('نبات الفوناريا', 'Funaria plant', 3, 3, 'object'),
('نبات النعناع', 'Mint plant', 3, 3, 'object'),
('ورقة سرخس مع أبواغ', 'Fern leaf with spores', 3, 3, 'object'),
('ساق كرفس', 'Celery stem', 3, 3, 'object'),
('بذور فاصولياء', 'Bean seeds', 3, 3, 'object'),
('نبات مائي', 'Aquatic plant', 3, 3, 'object'),
('ورقة مغطاة بورق ألومنيوم لمدة ٢٤ ساعة', 'A leaf covered with aluminum foil for 24 hours', 3, 3, 'object'),
('ورقة معرضة للضوء لفترة كافية', 'A leaf exposed to light for a sufficient period', 0, 0, 'object'),
('شريحة مُجهزة لطرف جذر بصل يخضع للانقسام الخلوي', 'Prepared slide of onion root tip undergoing cell division', 30, 1, 'object'); 
git add .
